language: java
jdk: openjdk8
addons:
  sonarcloud:
    organization: "spirotris"
    token:
      secure: "bbb1bOTQmCQaEcYygDP2FbrrfV3LnV1DpGNYNWuQ/fJjhbFj6Ft+9tAW/jPy4sfEWgn2sxs9ugs+pxCddQqANiK1nACRZiUFfVekmyxgL/vuY/uacOIF7XKBKKWxy7nJhIh81twyjkR8+0VLSMG1ngBLWxD4VJtj6/dycrlNYLRjfiz3qDaAsY0RsHGMOYSW6eqSxZ55+YeaqCSfyNYd0QO+d6K2XC1FM8odZO1G4qmJdYwgMwBDW9j6O4lnr+vXoAVLJN5mH9NT2t4TXy1uzgyk1PuQyRZb6n1n+mjdi5syorb2aRoe4UHAKIZwZ0kxeMwhGx0SV5zhHOzkfafGnMdeIJgAGtZDpx2ysotvKNHlGUB3UOgib2nHQEOFMfn8hsUoDzRqZCy297r6qEsZTj3wPvBsqQ3J7lzTiza1P2/ebiaJ+glg3Y1T8dBRDb6CdhzCRIhq0It4ysp6ojdWNjqa7ai6T35Wm6RoPXb5foMRD5omFC4cr/Mxv5RrPz5iY5fyT+X6f1BZHe2xqW5nbqj0gr/Nxd37LUI7BmmKZ/Wwjq9jUlOnC65zAyCjMCeM8PjvoLFolh/QIfAv+5yvSCjd0KdxcpuVigNx/fuZ77BWGkTiRI+ABWuPgTtzSMRAGhVDU4NJj0aox+Es2Gzl8WcNq0pKGAe5Pffzf9mxHNs="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
